name: deploy-to-digitalocean

on:
  push:
    branches:
      - main

env:
  SSH_HOST: 64.226.114.69
  SSH_PORT: 22
  SSH_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Install ssh-agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to droplet
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh_host: ${{ env.SSH_HOST }}
          ssh_port: ${{ env.SSH_PORT }}
          ssh_username: ${{ env.SSH_USERNAME }}
          ssh_private_key: ${{ env.SSH_PRIVATE_KEY }}
          source: build/
          target: /etc/nginx/sites-available
